import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {stageClip} from '../dist/stage-audio.js';
import {hydrateProfiles,syncProfile,selectProfile,exportProfile,validateExport,restoreProfile} from '../dist/progress-store.js';
import {normalizeAlphabetReading,readingAlphabet} from '../dist/alphabet-reading-data.js';
const report={checks:[],layouts:[],speeds:[]};
const p=hydrateProfiles(null);p.learning.alphabetReading=normalizeAlphabetReading({started:true,index:12,heard:['a','b'],mode:'all'});syncProfile(p,'little');const backup=validateExport(JSON.stringify(exportProfile(p,'little'))),target=hydrateProfiles(null);restoreProfile(target,backup);assert.deepEqual(target.learning.alphabetReading,p.learning.alphabetReading);selectProfile(target,'big');assert.equal(target.learning.alphabetReading,undefined);selectProfile(target,'little');assert.equal(target.learning.alphabetReading.index,12);assert.doesNotThrow(()=>validateExport(JSON.stringify(exportProfile(hydrateProfiles(null),'little'))));
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await context.addInitScript(()=>{const Native=Audio,play=HTMLMediaElement.prototype.play;window.clips=[];window.log=[];window.samples=[];window.blocked=false;window.overlap=false;
  HTMLMediaElement.prototype.play=function(...args){if(window.blocked)return Promise.reject(new DOMException('Autoplay blocked','NotAllowedError'));return play.apply(this,args);};
  window.Audio=function(...args){const a=new Native(...args),entry={path:new URL(a.src).pathname,rate:null,ended:false};window.clips.push(a);window.log.push(entry);a.addEventListener('playing',()=>{entry.rate=a.playbackRate;if(window.clips.filter(c=>!c.paused&&!c.ended).length>1)window.overlap=true;sample();});a.addEventListener('ended',()=>entry.ended=true);function sample(){if(a.paused||a.ended)return;const mark=document.querySelector('.alphabet-pair.speech-highlight'),controls=document.querySelector('.alphabet-reading-controls');if(mark&&controls){const b=mark.getBoundingClientRect(),c=controls.getBoundingClientRect();window.samples.push({path:entry.path,letter:mark.dataset.letter,visible:b.top>=c.bottom-1&&b.bottom<=innerHeight+1});}requestAnimationFrame(sample);}return a;};
 });
 const act=a=>page.locator('[data-action="'+a+'"]'),home=()=>act('home').first().click(),saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));
 async function seed(raw){await page.evaluate(v=>localStorage.setItem('little-english-v1',JSON.stringify(v)),raw);await page.reload();}
 await page.addInitScript(()=>localStorage.setItem('little-english-opening-audio-v1',JSON.stringify({version:1,enabled:false})));await page.goto('http://localhost:4174');assert.equal(await page.evaluate(()=>window.clips.length),0);await act('start-home').click();await expect(page.locator('h1')).toHaveText('Read the alphabet');assert.deepEqual(await page.locator('.alphabet-pair').allTextContents(),readingAlphabet.map(c=>c.toUpperCase()+c));
 await page.waitForFunction(()=>document.querySelector('.alphabet-pair.speech-highlight'));await act('stages-alphabet-pause').click();const frozen=await page.evaluate(()=>({t:window.clips.at(-1).currentTime,h:document.querySelector('.alphabet-pair.speech-highlight')?.dataset.letter}));await page.waitForTimeout(250);assert.deepEqual(await page.evaluate(()=>({t:window.clips.at(-1).currentTime,h:document.querySelector('.alphabet-pair.speech-highlight')?.dataset.letter})),frozen);await expect(act('stages-alphabet-pause')).toHaveText('Resume');await act('stages-alphabet-pause').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('little-english-v1')).learning.alphabetReading.finished,{},{timeout:60000});assert.deepEqual(await page.evaluate(()=>window.log.map(e=>e.path)),readingAlphabet.map(c=>stageClip('name:'+c)));assert((await saved()).learning.alphabetReading.heard.length===26);assert(await page.evaluate(()=>window.samples.every(s=>s.visible)));for(const s of await page.evaluate(()=>window.samples))assert.equal(s.path,stageClip('name:'+s.letter));report.speeds.push({speed:1,all26:true,actualHighlights:true,pauseResume:true,followVisible:true});
 await act('stages-alphabet-replay').click();await page.waitForFunction(()=>document.querySelector('.alphabet-pair.speech-highlight')?.dataset.letter==='a');await page.locator('.alphabet-pair[data-letter=m]').click();await page.waitForFunction(()=>document.querySelector('.alphabet-pair.speech-highlight')?.dataset.letter==='m');await page.waitForFunction(()=>window.clips.at(-1).ended);assert.equal((await saved()).learning.alphabetReading.mode,'single');const count=await page.evaluate(()=>window.clips.length);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>window.clips.length),count);await act('stages-alphabet-replay').click();assert.equal(await page.evaluate(()=>window.log.at(-1).path),stageClip('name:m'));await home();assert(await page.evaluate(()=>window.clips.every(a=>a.paused)));await expect(page.locator('.speech-highlight')).toHaveCount(0);await expect(act('continue-home')).toContainText('Read the alphabet');
 await seed({audioSpeed:.85});await act('start-home').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('little-english-v1')).learning.alphabetReading.finished,{},{timeout:70000});assert.deepEqual(await page.evaluate(()=>window.log.map(e=>e.path)),readingAlphabet.map(c=>stageClip('name:'+c)));assert(await page.evaluate(()=>window.log.every(e=>e.ended&&e.rate===.85)));report.speeds.push({speed:.85,all26:true,actualHighlights:true});await home();
 await seed({});await page.evaluate(()=>window.blocked=true);await act('start-home').click();await expect(page.locator('#audio-status')).toContainText('Tap Listen to all');await expect(page.locator('.speech-highlight')).toHaveCount(0);await expect(act('stages-alphabet-all')).toBeVisible();await page.evaluate(()=>window.blocked=false);await act('stages-alphabet-all').click();await page.waitForFunction(()=>document.querySelector('.alphabet-pair.speech-highlight'));await act('stages-alphabet-pause').click();await home();const position=(await saved()).learning.alphabetReading.index;await page.reload();await act('continue-home').click();assert.equal((await saved()).learning.alphabetReading.index,position);await act('stages-alphabet-pause').click();report.checks.push('Autoplay works when allowed; blocked autoplay exposes explicit Listen to all; saved reading position resumes without resetting other lessons');
 for(const width of [320,360,390,430,768,1366])for(const enlarged of [false,true]){await page.setViewportSize({width,height:900});await page.evaluate(enlarged=>document.documentElement.style.setProperty('font-size',enlarged?'32px':'16px','important'),enlarged);await page.waitForTimeout(50);const r=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,small:[...document.querySelectorAll('.alphabet-reading button')].filter(e=>{const b=e.getBoundingClientRect();return b.width<55.5||b.height<55.5;}).map(e=>e.textContent),clipped:[...document.querySelectorAll('.alphabet-pair')].filter(e=>{const b=e.getBoundingClientRect(),spans=[...e.querySelectorAll('span')];return spans.some(s=>{const z=s.getBoundingClientRect();return z.left<b.left+1||z.right>b.right-1;});}).map(e=>e.textContent)}));assert.equal(r.scroll,r.width);assert.deepEqual(r.small,[]);assert.deepEqual(r.clipped,[]);report.layouts.push({width,enlarged});}
 await page.evaluate(()=>document.documentElement.style.removeProperty('font-size'));await page.setViewportSize({width:390,height:844});await page.screenshot({path:'qa/alphabet-reading-390.png',fullPage:true});await act('stages-alphabet-next').click();await expect(page.locator('h1')).toContainText('Aa');await expect(act('stages-match-open')).toBeVisible();await act('stages-match-open').click();await expect(page.locator('h2')).toContainText('A matches a');assert(await page.evaluate(()=>window.clips.every(a=>a.paused)));assert.equal(await page.evaluate(()=>window.overlap),false);assert.deepEqual(errors,[]);
 report.checks.push('Ordered A–Z pairs; individual tap and Replay read one English name only; changing screens stops audio and clears highlights','Phone touch emulation, tablet and desktop; 200% text, no horizontal overflow or clipped letters; controls and pairs at least 56px','Matching and retained letter examples follow alphabet reading; profile isolation and versioned export/import preserve partial reading');report.passed=true;report.unverified=['Physical phone and tablet hardware','Independent human pronunciation review of reused English recordings'];await writeFile('qa/alphabet-reading-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));await context.close();
}finally{await browser.close();}
