import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {mathLessons,mathWords,mathSteps,mathReviewItems,mathAudioSpecs,mathQuestionId,normalizeMath} from '../dist/math-data.js';
import {mathScene} from '../dist/math-scenes.js';
import {hydrateProfiles,syncProfile,selectProfile,exportProfile,validateExport,restoreProfile} from '../dist/progress-store.js';
import {recordAttempt,dueItems,DAY,normalizePractice} from '../dist/practice-data.js';
import {stageSpeech} from '../dist/stage-speech.js';
import {audioTimings} from '../dist/audio-timings.js';
const report={lessons:[],questions:[],layouts:[],audio:[],checks:[]};
assert.equal(mathLessons.length,12);assert.equal(mathReviewItems.length,15);
for(const l of mathLessons){
 assert(!/^(Addition|Subtraction|Division|Measurement)$/i.test(l.title));
 const steps=mathSteps(l);assert(steps.every(s=>s.type!=='word'||s.meaning&&s.text&&mathScene(s.scene)));
 for(const q of [...l.questions,...(l.extra?.questions||[])]){assert.equal(q.choices.filter(c=>c.id===q.answer).length,1);assert.equal(new Set(q.choices.map(c=>c.id)).size,q.choices.length);assert(q.hint&&q.feedback&&q.meaning);q.choices.forEach(c=>assert(mathScene(c.scene)));}
 assert(steps.slice(0,l.words.length).every(s=>s.type==='word'));
 report.lessons.push({id:l.id,title:l.title,words:l.words,questions:l.questions.length,optionalLaterWords:l.extra?.words||[]});
}
assert.equal(mathWords.altogether.meaning,'সব মিলিয়ে / মোট');assert.equal(mathSteps(mathLessons[5]).find(s=>s.word==='each').meaning,'প্রতিটি');
const legacy=hydrateProfiles({profile:'little',completed:{little:['letters-sat'],big:['words-1']},learning:{letter:3},pictureFamilies:{writing:{drafts:{cat:{strokes:[]}}}}});
assert.equal(legacy.learning.math,undefined);const oldFile=validateExport(JSON.stringify(exportProfile(legacy,'little')));assert.equal(oldFile.data.learning.math,undefined);
legacy.learning.math=normalizeMath({current:'math-flowers',level:2,lessons:{'math-flowers':{step:3,answers:{count:'3'},attempts:{count:{tries:3,misses:2,assisted:true,firstCorrect:false}}}}});legacy.lastActivity={kind:'stage',page:'math-lesson',id:'math-flowers'};
recordAttempt(legacy.practice,'math:math-flowers:count',false,false,100*DAY);syncProfile(legacy,'little');selectProfile(legacy,'big');assert.equal(legacy.learning.math,undefined);assert.equal(legacy.practice.history.length,0);selectProfile(legacy,'little');
const file=validateExport(JSON.stringify(exportProfile(legacy,'little'))),fresh=hydrateProfiles(null);restoreProfile(fresh,file);assert.deepEqual(fresh.learning.math,legacy.learning.math);assert.deepEqual(fresh.completed.little,['letters-sat']);
fresh.learning.math.lessons['math-flowers'].step=5;restoreProfile(fresh,file);assert.equal(fresh.learning.math.lessons['math-flowers'].step,5);
for(const bad of [f=>f.data.learning.math.current='not-a-lesson',f=>f.data.learning.math.lessons['math-flowers'].step=999,f=>f.data.learning.math.lessons['math-flowers'].answers.count='8',f=>f.data.learning.math.lessons['math-flowers'].attempts.count.misses=-1]){const f=structuredClone(file);bad(f);assert.throws(()=>validateExport(JSON.stringify(f)));}
const pr=normalizePractice(null);let now=100*DAY;recordAttempt(pr,'math:math-flowers:count',false,false,now);assert.equal(pr.items['math:math-flowers:count'].due,now+DAY);assert(dueItems(pr,now+DAY).includes('math:math-flowers:count'));now+=DAY;for(const gap of [3,7,14]){recordAttempt(pr,'math:math-flowers:count',true,false,now);assert.equal(pr.items['math:math-flowers:count'].due,now+gap*DAY);now+=gap*DAY;}recordAttempt(pr,'math:math-flowers:count',true,true,now);assert.equal(pr.items['math:math-flowers:count'].due,now+DAY);
report.checks.push('12 stable lessons in requested order; 13 core questions and 2 optional later questions','Old progress and export shape stay compatible; profile isolation, validated roundtrip and additive restore preserve current positions','Missed maths questions use existing 1/3/7/14-day review; helped recall returns in 1 day');
const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[];
async function context(width,touch=false){const c=await browser.newContext({viewport:{width,height:width<720?844:1000},hasTouch:touch,serviceWorkers:'block'}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{localStorage.setItem('little-english-opening-audio-v1',JSON.stringify({version:1,enabled:false}));const fixture=sessionStorage.getItem('qa-math-fixture');if(fixture){localStorage.setItem('little-english-v1',fixture);sessionStorage.removeItem('qa-math-fixture');}const Native=Audio;window.clips=[];window.Audio=function(...args){const a=new Native(...args);window.clips.push(a);return a;};});await p.goto('http://localhost:4174');return {c,p};}
const act=(p,a)=>p.locator('[data-action="'+a+'"]');
async function seed(p,raw){await p.evaluate(raw=>sessionStorage.setItem('qa-math-fixture',JSON.stringify(raw)),raw);await p.reload();}
async function open(p,l,step=0,extra=false,speed=1){await seed(p,{audioSpeed:speed,learning:{math:normalizeMath({level:2,current:l.id,lessons:{[l.id]:{step,extra,extraStep:step}}})},lastActivity:{kind:'stage',page:'math-lesson',id:l.id}});await act(p,'continue-home').click();await expect(p.locator('.math-player')).toHaveAttribute('data-math-lesson',l.id);}
const saved=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));
async function layout(p,label){const result=await p.evaluate(()=>{const visible=e=>e.getClientRects().length,controls=[...document.querySelectorAll('button,select,.math-player summary,.math-parent-level summary')].filter(visible),bad=controls.filter(e=>{const r=e.getBoundingClientRect();return r.width<55.5||r.height<55.5;}).map(e=>({text:e.textContent.slice(0,60),w:e.offsetWidth,h:e.offsetHeight})),clipped=controls.filter(e=>{const r=e.getBoundingClientRect();return r.left<-.5||r.right>innerWidth+.5;}).map(e=>e.textContent.slice(0,50)),text=[...document.querySelectorAll('main p,main span,main label,main summary,nav button')].filter(e=>visible(e)&&!e.closest('svg')).map(e=>parseFloat(getComputedStyle(e).fontSize));return{width:innerWidth,scroll:document.documentElement.scrollWidth,bad,clipped,minText:Math.min(...text)};});assert.equal(result.scroll,result.width,label);assert.deepEqual(result.bad,[],label);assert.deepEqual(result.clipped,[],label);if(result.width<720)assert(result.minText>=16,label+' readable text');report.layouts.push({label,...result});}
try{
 for(const [width,touch]of [[390,true],[1366,false]]){const {c,p}=await context(width,touch);await expect(p.locator('.home-stage')).toHaveCount(6);await p.locator('.home-stage[data-stage=math]').click();await expect(p.locator('.math-lesson-card')).toHaveCount(12);await expect(p.locator('.math-lesson-card b')).toHaveText(mathLessons.map(l=>l.title));assert.equal((await saved(p))?.learning.math?.level??0,0);for(const level of ['1','2','0']){await p.locator('.math-parent-level summary').click();await p.locator('#math-level').selectOption(level);await expect(p.locator('.math-lesson-card')).toHaveCount(12);assert.equal((await saved(p)).learning.math.level,Number(level));}await p.screenshot({path:'qa/math-all-lessons-'+width+'.png',fullPage:true});
  // Every word, sentence, question and completion control on touch and mouse.
  for(const l of mathLessons){for(const extra of [false,...(l.extra?[true]:[])]){await open(p,l,0,extra);const steps=mathSteps(l,extra);for(let i=0;i<steps.length-1;i++){const st=steps[i];await expect(p.locator('.math-player')).toHaveAttribute('data-math-step',String(i));await expect(p.locator('.math-player')).toHaveAttribute('data-math-type',st.type);await expect(p.locator('.math-player>.math-scene')).toHaveAttribute('data-math-scene',st.scene);await expect(p.locator('.math-sentence')).toHaveText(st.type==='question'?st.prompt:st.text);
     if(st.type==='word'){await expect(p.locator('.math-vocab-word')).toHaveText(st.word);await p.locator('.math-meaning summary').click();await expect(p.locator('.math-meaning p')).toHaveText(st.meaning);await p.locator('.math-meaning summary').click();}
     if(st.type==='question'){await expect(act(p,'stages-math-next')).toBeDisabled();const wrong=st.choices.find(a=>a.id!==st.answer);await p.locator('[data-action=stages-math-answer][data-value="'+wrong.id+'"]').click();await expect(p.locator('.math-demonstration')).toContainText(st.choices.find(a=>a.id===st.answer).label);await expect(act(p,'stages-math-next')).toBeDisabled();await p.locator('[data-action=stages-math-answer][data-value="'+wrong.id+'"]').click();await expect(act(p,'stages-math-answer')).toHaveCount(2);await p.locator('[data-action=stages-math-answer][data-value="'+st.answer+'"]').click();await expect(p.locator('.math-feedback')).toContainText('✓');await expect(p.locator('.math-feedback')).toContainText(st.feedback);const raw=await saved(p),record=raw.learning.math.lessons[l.id];assert.equal(record.attempts[st.id].misses,2);assert.equal(record.attempts[st.id].assisted,true);assert.equal(record.answers[st.id],st.answer);assert.equal(raw.practice.history.at(-1).assisted,true);assert(raw.practice.items[mathQuestionId(l,st)].due>Date.now());await act(p,'stages-math-previous').click();await act(p,'stages-math-next').click();await expect(p.locator('.math-feedback')).toContainText(st.feedback);report.questions.push({width,touch,lesson:l.id,question:st.id,answer:st.answer,assisted:true,retainedOnPrevious:true});}
     await act(p,'stages-math-next').click();
    }await expect(p.locator('.math-star')).toHaveCount(1);assert.equal((await saved(p)).learning.math.lessons[l.id][extra?'extraDone':'done'],true);}
  }
  await c.close();
 }
 const {c,p}=await context(390,true),first=mathLessons[0];
 // Count actual SVG objects and inspect mathematical geometry, not only labels.
 const scenes=['flower-three','flowers-five','tree-three','tree-two','cake-cut','cake-shared','baskets','ribbons','ruler','cups','cup-full','clock-three','clock-half','shop','shop-change','chart','chart-difference'];
 await p.evaluate(async scenes=>{const {mathScene}=await import('/math-scenes.js');document.querySelector('main').innerHTML=scenes.map(s=>mathScene(s)).join('');},scenes);
 const n=(s,o)=>p.locator('[data-math-scene="'+s+'"] [data-object="'+o+'"]').count();assert.equal(await n('flower-three','flower'),3);assert.equal(await n('flowers-five','flower'),5);assert.equal(await n('tree-three','bird'),3);assert.equal(await n('tree-two','bird'),2);assert.equal(await n('cake-shared','brother'),3);assert.equal(await n('cake-shared','piece'),3);assert.equal(await n('baskets','basket'),3);assert.equal(await n('baskets','apple'),6);assert.equal(await n('chart','sticker'),5);assert.equal(await p.locator('[data-math-scene=cake-shared] [data-object=piece]').evaluateAll(es=>new Set(es.map(e=>e.getAttribute('d'))).size),1);
 const ribbons=await p.locator('[data-math-scene=ribbons] [data-object=ribbon]').evaluateAll(es=>es.map(e=>({x:e.getAttribute('x'),w:+e.getAttribute('width')})));assert.equal(ribbons[0].x,ribbons[1].x);assert(ribbons[0].w>ribbons[1].w);assert.equal(await p.locator('[data-math-scene=ruler] text').first().textContent(),'0');assert.equal(await p.locator('[data-math-scene=cups] [data-object=cup]').evaluateAll(es=>es.map(e=>+e.dataset.water).join(',')),'0.8,0.25');assert.equal(await p.locator('[data-math-scene=cup-full] [data-object=cup]').getAttribute('data-water'),'1');await expect(p.locator('[data-math-scene=clock-three] [data-clock-hour]')).toHaveAttribute('data-clock-minute','0');await expect(p.locator('[data-math-scene=clock-half] [data-clock-hour]')).toHaveAttribute('data-clock-minute','30');await expect(p.locator('[data-math-scene=shop]')).toContainText('৳5');await expect(p.locator('[data-math-scene=shop]')).toContainText('৳3');await expect(p.locator('[data-math-scene=shop-change]')).toContainText('৳2');
 report.checks.push('Visible counts and arithmetic agree: 2+3=5, 3−1=2, three equal 120° cake pieces, 3×2=6, ৳5+৳3=৳8 and ৳10−৳8=৳2','Aligned ribbons and ruler zero, identical-size clear cups, correct 3:00 and 3:30 hands, chart 3 vs 2 with one extra');
 // Actions finish in stable reading scenes; reduced motion shows final state.
 for(const [id,scene]of [['math-total-flowers','flowers-join'],['math-bird-away','bird-away'],['math-cake','cake-share'],['math-cups','cup-fill'],['math-clock','clock-move']]){const l=mathLessons.find(l=>l.id===id),i=mathSteps(l).findIndex(s=>s.type==='sentence'&&s.scene===scene);await open(p,l,i);assert(await p.evaluate(()=>document.getAnimations().some(a=>a.playState==='running')));await act(p,'stages-math-action').click();await p.waitForTimeout(1600);assert(await p.evaluate(()=>document.getAnimations().every(a=>a.playState==='finished')));}
 await p.emulateMedia({reducedMotion:'reduce'});await open(p,mathLessons[3],mathSteps(mathLessons[3]).findIndex(s=>s.scene==='bird-away'));assert.equal(await p.evaluate(()=>document.getAnimations().length),0);assert.equal(await p.locator('[data-motion=fly]').evaluate(e=>getComputedStyle(e).opacity),'0');await p.emulateMedia({reducedMotion:'no-preference'});
 // Per-profile Continue restores unfinished word/sentence, with no autoplay.
 await open(p,first,3);await act(p,'home').first().click();await expect(act(p,'continue-home')).toContainText(first.title);await p.reload();await act(p,'continue-home').click();await expect(p.locator('.math-player')).toHaveAttribute('data-math-step','3');await act(p,'parents').click();await expect(p.locator('.guide')).toContainText('English for Math · This profile');await act(p,'profile').filter({hasText:'Word Adventurer'}).click();await expect(p.locator('.guide')).not.toContainText('Flowers in the Garden · Counting');await act(p,'home').first().click();await expect(act(p,'start-home')).toBeVisible();assert.equal((await saved(p)).learning.math,undefined);await act(p,'parents').click();await act(p,'profile').filter({hasText:'Little Explorer'}).click();await act(p,'home').first().click();await expect(act(p,'continue-home')).toContainText(first.title);
 // A prior word introduction can be skipped in a new lesson without completion transfer.
 await seed(p,{learning:{math:normalizeMath({level:2,wordsMet:['flower','one','two','three','count','how many']})}});await p.locator('.home-stage[data-stage=math]').click();await p.locator('[data-action=stages-math-open][data-id=math-flowers]').click();await expect(p.locator('.math-player')).toHaveAttribute('data-math-type','sentence');assert.equal((await saved(p)).learning.math.lessons['math-flowers'].done,false);await act(p,'stages-math-previous').click();await expect(p.locator('.math-vocab-word')).toHaveText('how many');
 // Existing parent review renders maths picture choices and updates its schedule.
 const due=hydrateProfiles(null);for(let i=0;i<3;i++)recordAttempt(due.practice,'math:math-flowers:count',false,false,Date.now()-2*DAY+i);syncProfile(due,'little');await seed(p,due);await act(p,'parents').click();await expect(p.locator('.guide')).toContainText('Flowers in the Garden · Counting to three · 3 missed');await act(p,'practice-open-review').click();await expect(p.locator('h1')).toHaveText('How many flowers?');await p.locator('[data-action=practice-answer][data-value="3"]').click();await expect(p.locator('.feedback')).toContainText('There are three flowers');assert((await saved(p)).practice.items['math:math-flowers:count'].due>Date.now());
 report.checks.push('All twelve lesson cards are visible in order for new profiles and every saved parent level; level changes suggest starting lessons without hiding cards','All 12 full core flows plus both optional follow-ups completed using touch-capable phone and mouse desktop browsers','Specific hint, shown correct answer, two-choice helped retry, visible completed answer and manual Next; Previous retains answers','Home/reload Continue, per-profile parent reports, introduced-word skip without false completion, actual maths review all work','Join/fly/share/pour/clock actions stop after one animation; reduced motion preserves final reading scene');
 // Phone, tablet, desktop and enlarged text: scoped new pages plus unchanged stages.
 for(const width of [320,360,390,430,768,1366]){await p.setViewportSize({width,height:width<720?844:1000});for(const large of [false,true]){await seed(p,{learning:{math:normalizeMath({level:2})}});if(large)await p.evaluate(()=>document.documentElement.style.setProperty('font-size','32px','important'));await layout(p,'home '+width+' '+large);await p.locator('.home-stage[data-stage=math]').click();await layout(p,'math library '+width+' '+large);await p.locator('[data-action=stages-math-open][data-id=math-flowers]').click();await layout(p,'vocabulary '+width+' '+large);for(let i=0;i<6;i++)await act(p,'stages-math-next').click();await layout(p,'sentence '+width+' '+large);for(let i=0;i<4;i++)await act(p,'stages-math-next').click();await layout(p,'question '+width+' '+large);await act(p,'stages-math-answer').first().click();await layout(p,'helped retry '+width+' '+large);await act(p,'parents').click();await layout(p,'parents '+width+' '+large);if(!large&&[390,1366].includes(width)){await act(p,'home').first().click();await act(p,'continue-home').click();await p.screenshot({path:'qa/math-'+width+'.png',fullPage:true});}}}
 // All new recordings decode and their cues belong to the same recorded stream.
 for(const spec of mathAudioSpecs){const clip=stageSpeech[spec.key];assert(clip,spec.key);const meta=audioTimings[clip];assert.equal(meta.text,spec.text,spec.key);assert.equal(meta.voice,'en-GB-SoniaNeural');const bytes=await readFile('dist'+clip);const decoded=await p.evaluate(async b=>{const ctx=new AudioContext();try{const a=await ctx.decodeAudioData(Uint8Array.from(atob(b),x=>x.charCodeAt(0)).buffer);return{duration:a.duration,signal:a.getChannelData(0).some(v=>Math.abs(v)>.001)};}finally{await ctx.close();}},bytes.toString('base64'));assert(decoded.signal);assert(meta.words.length);assert(meta.words.every(w=>w.start>=0&&w.end<=decoded.duration+.15&&w.to<=meta.text.length));report.audio.push({key:spec.key,clip,duration:decoded.duration,cues:meta.words.length});}
 const before=JSON.parse(execFileSync('git',['show','HEAD:dist/stage-speech.js'],{encoding:'utf8'}).split('Object.freeze(')[1].split(');')[0]);for(const [key,clip]of Object.entries(before))assert.equal(stageSpeech[key],clip,'existing audio '+key);
 for(const speed of [1,.85]){await open(p,first,6,false,speed);await act(p,'stages-math-audio').click();await p.waitForFunction(()=>window.clips.at(-1)?.currentTime>0);assert.equal(await p.evaluate(()=>window.clips.at(-1).playbackRate),speed);await p.waitForFunction(()=>!!document.querySelector('.math-sentence .spoken-word[data-speech-active]'));const active=await p.locator('.math-sentence [data-speech-active]').allTextContents();assert.equal(active.length,1);await act(p,'stages-pause').click();const before=await p.evaluate(()=>({time:window.clips.at(-1).currentTime,word:document.querySelector('[data-speech-active]')?.textContent}));await p.waitForTimeout(180);assert.deepEqual(await p.evaluate(()=>({time:window.clips.at(-1).currentTime,word:document.querySelector('[data-speech-active]')?.textContent})),before);await act(p,'stages-pause').click();await act(p,'stages-math-audio').click();await p.waitForFunction(()=>window.clips.at(-1)?.currentTime>0);await act(p,'home').first().click();assert(await p.evaluate(()=>window.clips.every(a=>a.paused)));assert.equal(await p.locator('[data-speech-active]').count(),0);}
 await open(p,first,0);await act(p,'stages-math-audio').click();await p.waitForFunction(()=>!!document.querySelector('.math-vocab-word[data-speech-active]'));await act(p,'stages-math-next').click();assert(await p.evaluate(()=>window.clips.every(a=>a.paused)));assert.equal(await p.locator('[data-speech-active]').count(),0);
 await p.keyboard.press('Tab');assert(await p.evaluate(()=>document.activeElement.matches('button,a,summary,select')));assert(await p.locator('.math-player svg').getAttribute('aria-label'));await c.close();
 report.checks.push('Every maths vocabulary, sentence, question, hint and explanation clip decodes with recorded word timestamps; all prior audio mappings unchanged','Actual normal/slower MP3 playback, moving word highlight, paused highlight, Replay, Home and Next cancellation verified; vocabulary highlights whole word');
 assert.deepEqual(errors,[]);report.passed=true;report.limitations=['Audio was decoded and played by browser tests, but human-perceived pronunciation, clarity and teaching tone have not been listened to by the agent. Parent listening check is required.','Touch checks use Edge touch emulation, not physical iOS/Android devices.','Optional Bangla help is written; no new Bengali maths recording is claimed.'];await writeFile('qa/english-math-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:true,questions:report.questions.length,layouts:report.layouts.length,audio:report.audio.length,checks:report.checks}));
}finally{await browser.close();}
