import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {scienceLessons,scienceSteps,scienceReviewItems,scienceAudioSpecs,scienceQuestionId,normalizeScience} from '../dist/science-data.js';
import {scienceScene} from '../dist/science-scenes.js';
import {hydrateProfiles,syncProfile,selectProfile,exportProfile,validateExport,restoreProfile} from '../dist/progress-store.js';
import {recordAttempt,dueItems,DAY,normalizePractice} from '../dist/practice-data.js';
import {stageSpeech} from '../dist/stage-speech.js';
import {audioTimings} from '../dist/audio-timings.js';
const report={lessons:[],questions:[],experiments:[],layouts:[],audio:[],checks:[]};
assert.equal(scienceLessons.length,10);assert.equal(scienceReviewItems.length,18);assert.equal(new Set(scienceLessons.map(l=>l.id)).size,10);
for(const l of scienceLessons){const steps=scienceSteps(l);for(const s of steps.filter(s=>s.scene)){assert(s.meaning);assert(scienceScene(s.scene));if(s.type==='word')assert(s.word&&s.text);for(const o of s.action?.options||[])assert(o.text&&o.meaning&&scienceScene(o.scene));}for(const q of l.questions){assert.equal(q.choices.filter(c=>c.id===q.answer).length,1);assert.equal(new Set(q.choices.map(c=>c.id)).size,q.choices.length);assert(q.hint.startsWith('Thank you for trying.')&&q.feedback&&q.meaning);for(const c of q.choices)assert(scienceScene(c.scene));}report.lessons.push({id:l.id,title:l.title,words:l.words.map(w=>({word:w.word,meaning:w.meaning})),questions:l.questions.length});}
const legacy=hydrateProfiles({profile:'little',completed:{little:['letters-sat'],big:['words-1']},learning:{letter:3},pictureFamilies:{writing:{drafts:{cat:{strokes:[]}}}}});assert.equal(legacy.learning.science,undefined);assert.equal(validateExport(JSON.stringify(exportProfile(legacy,'little'))).data.learning.science,undefined);
legacy.learning.science=normalizeScience({current:'science-float',lessons:{'science-float':{step:4,experiments:{'water-test':{value:'key',tried:['wood','key']}},answers:{sank:'key'},attempts:{sank:{tries:3,misses:2,assisted:true,firstCorrect:false}}}}});legacy.lastActivity={kind:'stage',page:'science-lesson',id:'science-float'};recordAttempt(legacy.practice,'science:science-float:sank',false,false,100*DAY);syncProfile(legacy,'little');selectProfile(legacy,'big');assert.equal(legacy.learning.science,undefined);assert.equal(legacy.practice.history.length,0);selectProfile(legacy,'little');const file=validateExport(JSON.stringify(exportProfile(legacy,'little'))),fresh=hydrateProfiles(null);restoreProfile(fresh,file);assert.deepEqual(fresh.learning.science,legacy.learning.science);assert.deepEqual(fresh.completed.little,['letters-sat']);fresh.learning.science.lessons['science-float'].step=5;restoreProfile(fresh,file);assert.equal(fresh.learning.science.lessons['science-float'].step,5);
for(const bad of [f=>f.data.learning.science.current='unknown',f=>f.data.learning.science.lessons['science-float'].step=999,f=>f.data.learning.science.lessons['science-float'].answers.sank='unknown',f=>f.data.learning.science.lessons['science-float'].experiments['water-test'].tried.push('unknown'),f=>f.data.learning.science.lessons['science-float'].attempts.sank.misses=-1]){const f=structuredClone(file);bad(f);assert.throws(()=>validateExport(JSON.stringify(f)));}
const pr=normalizePractice(null),qid='science:science-float:sank';let now=100*DAY;recordAttempt(pr,qid,false,false,now);assert.equal(pr.items[qid].due,now+DAY);assert(dueItems(pr,now+DAY).includes(qid));now+=DAY;for(const gap of [3,7,14]){recordAttempt(pr,qid,true,false,now);assert.equal(pr.items[qid].due,now+gap*DAY);now+=gap*DAY;}recordAttempt(pr,qid,true,true,now);assert.equal(pr.items[qid].due,now+DAY);
report.checks.push('Ten stable lessons; every vocabulary scene, contextual Bangla meaning and unique supported question validated','Old progress/export shape retained; separate profiles, validated export/restore and additive restoration preserve existing work','Missed science questions use existing 1/3/7/14-day intervals; assisted recall returns in one day');
const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[];
const act=(p,a)=>p.locator('[data-action="'+a+'"]'),saved=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));
async function context(width,touch=false){const c=await browser.newContext({viewport:{width,height:width<720?844:1000},hasTouch:touch,serviceWorkers:'block'}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{localStorage.setItem('little-english-opening-audio-v1',JSON.stringify({version:1,enabled:false}));const raw=sessionStorage.getItem('qa-science-fixture');if(raw){localStorage.setItem('little-english-v1',raw);sessionStorage.removeItem('qa-science-fixture');}const Native=Audio;window.clips=[];window.Audio=function(...args){const a=new Native(...args);window.clips.push(a);return a;};});await p.goto('http://localhost:4174');return{c,p};}
async function seed(p,raw){await p.evaluate(raw=>sessionStorage.setItem('qa-science-fixture',JSON.stringify(raw)),raw);await p.reload();}
async function open(p,l,step=0,speed=1){await seed(p,{audioSpeed:speed,learning:{science:normalizeScience({current:l.id,lessons:{[l.id]:{step}}})},lastActivity:{kind:'stage',page:'science-lesson',id:l.id}});await act(p,'continue-home').click();await expect(p.locator('.science-player')).toHaveAttribute('data-science-lesson',l.id);}
async function layout(p,label){const r=await p.evaluate(()=>{const visible=e=>e.getClientRects().length,controls=[...document.querySelectorAll('button,select,.science-player summary,.science-parent summary')].filter(visible);const bad=controls.filter(e=>{const r=e.getBoundingClientRect();return r.width<55.5||r.height<55.5;}).map(e=>({text:e.textContent.slice(0,60),w:e.offsetWidth,h:e.offsetHeight}));const clipped=controls.filter(e=>{const r=e.getBoundingClientRect();return r.left<-.5||r.right>innerWidth+.5;}).map(e=>e.textContent.slice(0,50));const text=[...document.querySelectorAll('main p,main span,main label,main summary,nav button')].filter(e=>visible(e)&&!e.closest('svg')).map(e=>parseFloat(getComputedStyle(e).fontSize));return{width:innerWidth,scroll:document.documentElement.scrollWidth,bad,clipped,minText:Math.min(...text)};});assert.equal(r.scroll,r.width,label);assert.deepEqual(r.bad,[],label);assert.deepEqual(r.clipped,[],label);if(r.width<720)assert(r.minText>=16,label+' text');report.layouts.push({label,...r});}
try{
 for(const [width,touch]of [[390,true],[1366,false]]){const {c,p}=await context(width,touch);await expect(p.locator('.home-stage')).toHaveCount(6);await p.locator('.home-stage[data-stage=science]').click();await expect(p.locator('.science-lesson-card')).toHaveCount(10);
  for(const l of scienceLessons){await open(p,l);const steps=scienceSteps(l);for(let i=0;i<steps.length-1;i++){const st=steps[i];await expect(p.locator('.science-player')).toHaveAttribute('data-science-step',String(i));await expect(p.locator('.science-player')).toHaveAttribute('data-science-type',st.type);await expect(p.locator('.science-player>.science-scene')).toHaveAttribute('data-science-scene',st.scene);await expect(p.locator('.science-sentence')).toHaveText(st.type==='question'?st.prompt:st.text);
    if(st.type==='word'){await expect(p.locator('.science-vocab-word')).toHaveText(st.word);assert(await p.locator('.science-vocab-word').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=32));await p.locator('.science-meaning summary').click();await expect(p.locator('.science-meaning p')).toHaveText(st.meaning);await p.locator('.science-meaning summary').click();}
    if(st.action){await expect(act(p,'stages-science-next')).toBeDisabled();for(const o of st.action.options){const b=p.locator('[data-action=stages-science-explore][data-value="'+o.id+'"]');touch?await b.tap():await b.click();await expect(p.locator('.science-player>.science-scene')).toHaveAttribute('data-science-scene',o.scene);await expect(p.locator('.science-sentence')).toHaveText(o.text);await expect(b).toHaveAttribute('aria-pressed','true');const e=(await saved(p)).learning.science.lessons[l.id].experiments[st.action.id];assert(e.tried.includes(o.id));report.experiments.push({width,touch,lesson:l.id,action:st.action.id,option:o.id,scene:o.scene});}await expect(act(p,'stages-science-next')).toBeEnabled();}
    if(st.type==='question'){await expect(act(p,'stages-science-next')).toBeDisabled();const wrong=st.choices.find(c=>c.id!==st.answer);for(let n=0;n<2;n++){const b=p.locator('[data-action=stages-science-answer][data-value="'+wrong.id+'"]');touch?await b.tap():await b.click();await expect(p.locator('.science-demonstration')).toContainText(st.choices.find(c=>c.id===st.answer).label);await expect(act(p,'stages-science-next')).toBeDisabled();}await expect(act(p,'stages-science-answer')).toHaveCount(2);await p.locator('[data-action=stages-science-answer][data-value="'+st.answer+'"]').click();await expect(p.locator('.science-feedback')).toContainText('✓ '+st.feedback);const raw=await saved(p),a=raw.learning.science.lessons[l.id].attempts[st.id];assert.equal(a.misses,2);assert.equal(a.assisted,true);assert.equal(a.firstCorrect,false);assert.equal(raw.practice.history.at(-1).assisted,true);assert(raw.practice.items[scienceQuestionId(l,st)].due>Date.now());await act(p,'stages-science-previous').click();await act(p,'stages-science-next').click();await expect(p.locator('.science-feedback')).toContainText(st.feedback);report.questions.push({width,touch,lesson:l.id,question:st.id,assisted:true,retainedOnPrevious:true});}
    await act(p,'stages-science-next').click();
   }await expect(p.locator('.math-star')).toHaveCount(1);assert.equal((await saved(p)).learning.science.lessons[l.id].done,true);
  }await c.close();
 }
 const {c,p}=await context(390,true),first=scienceLessons[0];
 // Actual scene movement, finite animation and responsive final states.
 for(const [id,action,value,motion]of [['science-sunlight','days','later','bowl'],['science-day-night','turn','night','turn'],['science-float','water-test','key','water-object'],['science-push-pull','push','push','push'],['science-push-pull','pull','pull','pull'],['science-magnet','magnet-test','clip','attract']]){const l=scienceLessons.find(l=>l.id===id),step=scienceSteps(l).findIndex(s=>s.action?.id===action);await open(p,l,step);await p.locator('[data-action=stages-science-explore][data-value="'+value+'"]').click();const node=p.locator('.science-player [data-science-motion="'+motion+'"]');await expect(node).toHaveCount(1);const before=await node.evaluate(e=>getComputedStyle(e).transform);assert(await p.evaluate(()=>document.getAnimations().some(a=>a.playState==='running')));await p.waitForTimeout(1900);const after=await node.evaluate(e=>getComputedStyle(e).transform);assert.notEqual(before,after,id+' moves');assert(await p.evaluate(()=>document.getAnimations().every(a=>a.playState==='finished')));await act(p,'stages-science-animation').click();assert(await p.evaluate(()=>document.getAnimations().some(a=>a.playState==='running')));}
 const sw=scienceLessons[9];await open(p,sw,4);await p.locator('[data-action=stages-science-explore][data-value=on]').click();await expect(p.locator('.science-player [data-science-object=lamp-glow]')).toHaveCount(1);await p.locator('[data-action=stages-science-explore][data-value=off]').click();await expect(p.locator('.science-player [data-science-object=lamp-glow]')).toHaveCount(0);
 await p.emulateMedia({reducedMotion:'reduce'});await open(p,scienceLessons[5],5);await p.locator('[data-action=stages-science-explore][data-value=night]').click();assert.equal(await p.evaluate(()=>document.getAnimations().length),0);assert.equal(await p.locator('.science-player [data-science-motion=turn]').evaluate(e=>getComputedStyle(e).transform),'matrix(-1, 0, 0, -1, 0, 0)');await p.emulateMedia({reducedMotion:'no-preference'});
 // Inspect the model geometry and scientific evidence instead of labels alone.
 await p.evaluate(async()=>{const{scienceScene}=await import('/science-scenes.js');document.querySelector('main').innerHTML=['plants-start','plants-covered','plants-revealed','vapour-rise','cloud-form','earth-day','earth-night','float-wood','float-key','float-ball','magnet-clip','magnet-foil','pull-start'].map(s=>scienceScene(s)).join('');});
 assert.equal(await p.locator('[data-science-scene=plants-start] [data-grass-color=green]').count(),2);assert.equal(await p.locator('[data-science-scene=plants-covered] [data-science-object=opaque-bowl]').count(),1);assert.equal(await p.locator('[data-science-scene=plants-revealed] [data-grass-color=pale]').count(),1);assert.equal(await p.locator('[data-science-scene=vapour-rise] [data-science-object=vapour-arrows]').count(),1);assert.equal(await p.locator('[data-science-scene=vapour-rise] circle').count(),1);assert.equal(await p.locator('[data-science-scene=cloud-form] [data-science-drops=tiny] circle').count(),12);assert.equal(await p.locator('[data-science-scene=magnet-foil] [data-science-motion=attract]').count(),0);assert.equal(await p.locator('[data-science-scene=pull-start] [data-science-rope]').getAttribute('x2'),'370');
 report.checks.push('Actual bowl reveal, Earth turn, objects entering water, push/pull and magnetic attraction animate and stop; replay restarts; lamp switch changes glow; reduced motion shows final state','Same initial green patches and opaque cover; invisible vapour arrows separate from cloud droplets; aluminium stays still; pull rope connects to the wagon');
 // Continue saves unfinished experiment; no narration on Home or resume.
 const fl=scienceLessons[6];await open(p,fl,4);await p.locator('[data-action=stages-science-explore][data-value=key]').click();await act(p,'home').first().click();await p.reload();await expect(act(p,'continue-home')).toContainText(fl.title);await act(p,'continue-home').click();await expect(p.locator('.science-player')).toHaveAttribute('data-science-step','4');await expect(p.locator('.science-player>.science-scene')).toHaveAttribute('data-science-scene','float-key');await expect(act(p,'stages-science-next')).toBeDisabled();assert(await p.evaluate(()=>window.clips.every(a=>a.paused)));await act(p,'parents').click();await expect(p.locator('.guide')).toContainText('English for Science · This profile');await act(p,'profile').filter({hasText:'Word Adventurer'}).click();await expect(p.locator('.guide')).not.toContainText('Float or Sink? · saved step');assert.equal((await saved(p)).learning.science,undefined);await act(p,'profile').filter({hasText:'Little Explorer'}).click();await act(p,'home').first().click();await expect(act(p,'continue-home')).toContainText(fl.title);
 const due=hydrateProfiles(null);for(let i=0;i<3;i++)recordAttempt(due.practice,qid,false,false,Date.now()-2*DAY+i);syncProfile(due,'little');await seed(p,due);await act(p,'parents').click();await expect(p.locator('.guide')).toContainText('Float or Sink? · 3 missed');await act(p,'practice-open-review').click();await expect(p.locator('h1')).toHaveText('Which object sank in our test?');await p.locator('[data-action=practice-answer][data-value=key]').click();await expect(p.locator('.feedback')).toContainText('solid steel key sank');assert((await saved(p)).practice.items[qid].due>Date.now());
 // New stage and all focused screens at normal and doubled text sizes.
 for(const width of [320,360,390,430,768,1366])for(const large of [false,true]){await p.setViewportSize({width,height:width<720?844:1000});await seed(p,{});if(large)await p.evaluate(()=>document.documentElement.style.setProperty('font-size','32px','important'));await layout(p,'home '+width+' '+large);await p.locator('.home-stage[data-stage=science]').click();await layout(p,'library '+width+' '+large);await p.locator('[data-action=stages-science-open][data-id=science-sunlight]').click();await layout(p,'word '+width+' '+large);for(let i=0;i<6;i++)await act(p,'stages-science-next').click();await layout(p,'experiment '+width+' '+large);await act(p,'stages-science-explore').click();await layout(p,'revealed sentence '+width+' '+large);await act(p,'stages-science-next').click();await act(p,'stages-science-next').click();await layout(p,'question '+width+' '+large);await p.locator('[data-action=stages-science-answer][data-value=covered]').click();await layout(p,'wrong answer '+width+' '+large);await p.locator('[data-action=stages-science-answer][data-value=sun]').click();await act(p,'stages-science-next').click();await layout(p,'recap '+width+' '+large);await act(p,'stages-science-next').click();await layout(p,'finish '+width+' '+large);if(!large&&[390,1366].includes(width)){await act(p,'stages-science-revisit').click();await p.screenshot({path:'qa/science-'+width+'.png',fullPage:true});}await act(p,'parents').click();await layout(p,'parents '+width+' '+large);}
 for(const spec of scienceAudioSpecs){const clip=stageSpeech[spec.key];assert(clip,spec.key);const meta=audioTimings[clip];assert.equal(meta.text,spec.text);assert.equal(meta.voice,'en-GB-SoniaNeural');const bytes=await readFile('dist'+clip);const decoded=await p.evaluate(async b=>{const ctx=new AudioContext();try{const a=await ctx.decodeAudioData(Uint8Array.from(atob(b),x=>x.charCodeAt(0)).buffer);return{duration:a.duration,signal:a.getChannelData(0).some(v=>Math.abs(v)>.001)};}finally{await ctx.close();}},bytes.toString('base64'));assert(decoded.signal&&meta.words.length);assert(meta.words.every(w=>w.start>=0&&w.end<=decoded.duration+.15&&w.to<=meta.text.length));report.audio.push({key:spec.key,clip,duration:decoded.duration,cues:meta.words.length});}
 const before=JSON.parse(execFileSync('git',['show','HEAD:dist/stage-speech.js'],{encoding:'utf8'}).split('Object.freeze(')[1].split(');')[0]);for(const [key,clip]of Object.entries(before))assert.equal(stageSpeech[key],clip,'existing audio '+key);
 for(const speed of [1,.85]){await open(p,first,4,speed);await act(p,'stages-science-audio').click();await p.waitForFunction(()=>window.clips.at(-1)?.currentTime>0);assert.equal(await p.evaluate(()=>window.clips.at(-1).playbackRate),speed);await p.waitForFunction(()=>!!document.querySelector('.science-sentence .spoken-word[data-speech-active]'));assert.equal(await p.locator('.science-sentence [data-speech-active]').count(),1);await act(p,'stages-pause').click();const paused=await p.evaluate(()=>({time:window.clips.at(-1).currentTime,word:document.querySelector('[data-speech-active]')?.textContent}));await p.waitForTimeout(180);assert.deepEqual(await p.evaluate(()=>({time:window.clips.at(-1).currentTime,word:document.querySelector('[data-speech-active]')?.textContent})),paused);await act(p,'stages-pause').click();await act(p,'stages-science-audio').click();await p.waitForFunction(()=>window.clips.at(-1)?.currentTime>0);assert.equal(await p.evaluate(()=>window.clips.filter(a=>!a.paused).length),1);await act(p,'home').first().click();assert(await p.evaluate(()=>window.clips.every(a=>a.paused)));assert.equal(await p.locator('[data-speech-active]').count(),0);}
 await open(p,first);await act(p,'stages-science-audio').click();await p.waitForFunction(()=>!!document.querySelector('.science-vocab-word[data-speech-active]'));await act(p,'stages-science-next').click();assert(await p.evaluate(()=>window.clips.every(a=>a.paused)));assert.equal(await p.locator('[data-speech-active]').count(),0);
 await open(p,sw,4);await p.locator('[data-action=stages-science-explore][data-value=on]').focus();await p.keyboard.press('Enter');await expect(p.locator('.science-player>.science-scene')).toHaveAttribute('data-science-scene','lamp-on');await p.locator('[data-action=stages-science-explore][data-value=off]').focus();await p.keyboard.press('Space');await expect(p.locator('.science-player>.science-scene')).toHaveAttribute('data-science-scene','lamp-off');assert(await p.locator('.science-player>.science-scene').getAttribute('aria-label'));await c.close();
 report.checks.push('All ten complete lesson flows, all experiment options and all 18 questions tested with touch-capable phone and mouse desktop','Shown correct answer, useful spoken hint, easier assisted retry, manual Next and preserved Previous work','Home/reload Continue restores selected experiment and visited options; profile-specific reports and due picture review work','Every science recording decodes with real word timestamps; normal/slower playback, Pause/Resume, Replay, non-overlap and navigation cancellation tested; prior audio mappings unchanged','Keyboard Enter/Space and labelled SVG scenes work');assert.deepEqual(errors,[]);report.passed=true;report.limitations=['Browser playback and timing checked, but human-perceived English pronunciation, clarity and teaching tone require a parent listening check.','Touch tests use Edge emulation, not physical iOS/Android hardware.','Science Bangla meanings are written hints; no new Bangla recording is claimed.'];await writeFile('qa/english-science-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:true,questions:report.questions.length,experiments:report.experiments.length,layouts:report.layouts.length,audio:report.audio.length,checks:report.checks}));
}finally{await browser.close();}
