import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile,readFile} from 'node:fs/promises';
import {openingAudioSource} from '../dist/opening-audio-data.js';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--autoplay-policy=no-user-gesture-required']}),report={checks:[],viewports:[],humanListeningVerified:false};
assert.equal(openingAudioSource.voice,'ar-SA-ZariyahNeural');assert.equal(openingAudioSource.rate,'-8%');assert.equal(openingAudioSource.volume,'-15%');assert.equal(openingAudioSource.pitch,'+0Hz');assert.equal(openingAudioSource.spokenText,openingAudioSource.text.replaceAll('، ','. ')+'.');assert.notEqual(openingAudioSource.clip,'/audio/acb71904d7476ac0f80487c1.mp3');
try{
 for(const width of [390,1366]){
 const context=await browser.newContext({viewport:{width,height:844},hasTouch:width===390,serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const play=HTMLMediaElement.prototype.play;window.clips=[];window.blocked=false;HTMLMediaElement.prototype.play=function(...args){window.clips.push(this);return window.blocked?Promise.reject(new DOMException('Blocked','NotAllowedError')):play.apply(this,args);};});
 await page.goto('http://localhost:4174');await page.waitForFunction(()=>window.clips[0]?.currentTime>0);assert.equal(await page.evaluate(()=>new URL(window.clips[0].src).pathname),openingAudioSource.clip);await page.locator('[data-action=start-home]').click();await expect(page.locator('h1')).toHaveText('Read the alphabet',{timeout:30000});assert.equal(await page.evaluate(()=>window.clips.filter(a=>!a.paused&&!a.ended).length),1);await page.locator('[data-action=home]').first().click();await page.locator('.home-words').click();assert.equal(await page.evaluate(clip=>window.clips.filter(a=>a.src.endsWith(clip)).length,openingAudioSource.clip),0); // Completed opening source is cleared; no replay during navigation.
 await page.locator('[data-action=parents]').click();await expect(page.locator('#opening-audio-enabled')).toBeChecked();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));await page.locator('#opening-audio-enabled').uncheck();await page.reload();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.clips.length),0);await page.locator('[data-action=parents]').click();await expect(page.locator('#opening-audio-enabled')).not.toBeChecked();await page.locator('#opening-audio-enabled').check();await page.reload();await page.waitForFunction(()=>window.clips[0]?.currentTime>0);await page.locator('[data-action=opening-stop]').click();assert(await page.evaluate(()=>window.clips.every(a=>a.paused)));const restored=await page.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));assert.deepEqual(restored.learning,saved.learning);assert.deepEqual(restored.profileData,saved.profileData);report.checks.push(width+'px: default on, real opening playback, lesson waits for ending, Stop, no restart during page navigation, persistent off/on control, profile progress unchanged');
 await page.addInitScript(()=>window.blocked=true);await page.reload();await expect(page.locator('[data-action=opening-begin]')).toBeVisible();await page.evaluate(()=>window.blocked=false);await page.locator('[data-action=continue-home]').click();await expect(page.locator('h1')).toHaveText('Read the alphabet',{timeout:30000});assert.equal(await page.evaluate(()=>window.clips.filter(a=>!a.paused&&!a.ended).length),1);await page.locator('[data-action=home]').first().click();report.checks.push('Blocked autoplay shows Tap to begin; first learning tap plays opening once before lesson; no overlapping audio');
 const clips=[openingAudioSource.clip,'/audio/acb71904d7476ac0f80487c1.mp3'],decoded=[];for(const clip of clips){const bytes=(await readFile('dist'+clip)).toString('base64');decoded.push(await page.evaluate(async b64=>{const c=new AudioContext();try{const a=await c.decodeAudioData(Uint8Array.from(atob(b64),c=>c.charCodeAt(0)).buffer),samples=a.getChannelData(0);let peak=0,power=0,voicedPower=0,voiced=0;for(const x of samples){peak=Math.max(peak,Math.abs(x));power+=x*x;if(Math.abs(x)>.004){voiced++;voicedPower+=x*x;}}return{duration:a.duration,audible:peak>.01,peak,rms:Math.sqrt(power/samples.length),voicedRms:Math.sqrt(voicedPower/voiced)};}finally{await c.close();}},bytes));}assert(decoded[0].audible);assert(decoded[0].duration>decoded[1].duration);assert(decoded[0].voicedRms<decoded[1].voicedRms);assert(decoded[0].peak<1);assert.deepEqual(errors,[]);report.viewports.push({width,touch:width===390,passed:true});report.decoded={updated:decoded[0],previous:decoded[1]};await context.close();
 }
 report.passed=true;report.limitations=['Playback, duration and signal levels were checked; they do not verify pronunciation or perceived warmth','Fluent Arabic listening is still required for all three phrases; this synthetic recording has not been human-verified'];await writeFile('qa/opening-audio-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{await browser.close();}
