import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile,readFile} from 'node:fs/promises';
import {openingAudioSource} from '../dist/opening-audio-data.js';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--autoplay-policy=no-user-gesture-required']}),report={checks:[],humanListeningVerified:false};
try{
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const play=HTMLMediaElement.prototype.play;window.clips=[];window.blocked=false;HTMLMediaElement.prototype.play=function(...args){window.clips.push(this);return window.blocked?Promise.reject(new DOMException('Blocked','NotAllowedError')):play.apply(this,args);};});
 await page.goto('http://localhost:4174');await page.waitForFunction(()=>window.clips[0]?.currentTime>0);assert.equal(await page.evaluate(()=>new URL(window.clips[0].src).pathname),openingAudioSource.clip);await page.locator('[data-action=start-home]').click();await expect(page.locator('h1')).toHaveText('Read the alphabet',{timeout:30000});assert.equal(await page.evaluate(()=>window.clips.filter(a=>!a.paused&&!a.ended).length),1);await page.locator('[data-action=home]').first().click();await page.locator('.home-words').click();assert.equal(await page.evaluate(clip=>window.clips.filter(a=>a.src.endsWith(clip)).length,openingAudioSource.clip),0); // Completed opening source is cleared; no replay during navigation.
 await page.locator('[data-action=parents]').click();await expect(page.locator('#opening-audio-enabled')).toBeChecked();await page.locator('#opening-audio-enabled').uncheck();await page.reload();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.clips.length),0);await page.locator('[data-action=parents]').click();await expect(page.locator('#opening-audio-enabled')).not.toBeChecked();await page.locator('#opening-audio-enabled').check();await page.reload();await page.waitForFunction(()=>window.clips[0]?.currentTime>0);await page.locator('[data-action=opening-stop]').click();assert(await page.evaluate(()=>window.clips.every(a=>a.paused)));report.checks.push('Default on, real opening playback, lesson waits for ending, Stop, no restart during page navigation, persistent off/on control');
 await page.addInitScript(()=>window.blocked=true);await page.reload();await expect(page.locator('[data-action=opening-begin]')).toBeVisible();await page.evaluate(()=>window.blocked=false);await page.locator('[data-action=continue-home]').click();await expect(page.locator('h1')).toHaveText('Read the alphabet',{timeout:30000});assert.equal(await page.evaluate(()=>window.clips.filter(a=>!a.paused&&!a.ended).length),1);await page.locator('[data-action=home]').first().click();report.checks.push('Blocked autoplay shows Tap to begin; first learning tap plays opening once before lesson; no overlapping audio');
 const bytes=(await readFile('dist'+openingAudioSource.clip)).toString('base64');report.decoded=await page.evaluate(async b64=>{const c=new AudioContext();try{const a=await c.decodeAudioData(Uint8Array.from(atob(b64),c=>c.charCodeAt(0)).buffer);return{duration:a.duration,audible:a.getChannelData(0).some(x=>Math.abs(x)>.01)};}finally{await c.close();}},bytes);assert(report.decoded.audible);assert(report.decoded.duration>4);assert.deepEqual(errors,[]);report.passed=true;report.limitations=['Arabic pronunciation, ordinary tone and perceived similarity to Sonia require fluent human listening; synthetic Arabic uses Zariyah rather than an English voice'];await writeFile('qa/opening-audio-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));await context.close();
}finally{await browser.close();}
