import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile,readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {stageSpeech} from '../dist/stage-speech.js';
import {audioTimings} from '../dist/audio-timings.js';
import {playfulLesson} from '../dist/playful-data.js';
const old=JSON.parse(execFileSync('git',['show','9967f98:dist/stage-speech.js'],{encoding:'utf8'}).split('Object.freeze(')[1].split(');')[0]);for(const [key,value]of Object.entries(old))assert.equal(stageSpeech[key],value,'Changed old audio '+key);
const newClips=[...new Set(Object.entries(stageSpeech).filter(([key])=>!(key in old)).map(([,clip])=>clip))];
for(const clip of newClips){const bytes=await readFile('dist'+clip);assert(bytes.length>500,clip);const m=audioTimings[clip];assert(m&&m.words.length,clip);assert(m.words.every((w,i)=>w.start>=0&&w.end>w.start&&w.to>w.from&&w.to<=m.text.length&&(!i||w.start>=m.words[i-1].start)),clip);}
const report={preservedMappings:Object.keys(old).length,newRecordings:newClips.length,decoded:[],playback:[],limitations:['No human listening assessment of pronunciation, warmth or voice clarity has been performed.','Arabic remains the existing separate phrase recording; whole-phrase highlighting where word timestamps are unavailable.']};
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{localStorage.setItem('little-english-opening-audio-v1',JSON.stringify({version:1,enabled:false}));const fixture=sessionStorage.getItem('audio-fixture');if(fixture){localStorage.setItem('little-english-v1',fixture);sessionStorage.removeItem('audio-fixture');}const Native=Audio;window.playfulClips=[];window.Audio=function(...args){const a=new Native(...args);window.playfulClips.push(a);return a;};});await p.goto('http://localhost:4174');
// Decode actual audio and measure its signal. This proves a non-silent file,
// not a human judgment of accent or pronunciation.
for(let i=0;i<newClips.length;i+=15){const clips=newClips.slice(i,i+15);const decoded=await p.evaluate(async clips=>{const ac=new AudioContext();const out=await Promise.all(clips.map(async clip=>{const b=await ac.decodeAudioData(await(await fetch(clip)).arrayBuffer()),samples=b.getChannelData(0);let sum=0,peak=0;for(const sample of samples){sum+=sample*sample;peak=Math.max(peak,Math.abs(sample));}return{clip,duration:b.duration,rms:Math.sqrt(sum/samples.length),peak};}));await ac.close();return out;},clips);for(const r of decoded){assert(r.duration>.2&&r.rms>.0001,r.clip);const m=audioTimings[r.clip];assert(m.words.at(-1).end<r.duration+.5,r.clip+' timing exceeds audio');}report.decoded.push(...decoded);}
async function open(id,type,speed=1){const step=playfulLesson(id).steps.findIndex(s=>s.type===type),raw={audioSpeed:speed,learning:{playful:{current:id,lessons:{[id]:{step}}}},lastActivity:{kind:'playful',id}};await p.evaluate(raw=>sessionStorage.setItem('audio-fixture',JSON.stringify(raw)),raw);await p.reload();await p.locator('[data-action=continue-home]').click();}
for(const speed of [1,.85]){
 await open('science:science-body','explore',speed);await p.locator('button[data-action=playful-explore][data-value=brain]').click();await expect.poll(()=>p.evaluate(()=>window.playfulClips.at(-1)?.currentTime||0)).toBeGreaterThan(.1);await expect.poll(()=>p.locator('[data-speech-active]').count()).toBeGreaterThan(0);assert.equal(await p.evaluate(()=>window.playfulClips.at(-1).playbackRate),speed);await p.locator('[data-action=playful-pause]').click();const frozen=await p.evaluate(()=>({time:window.playfulClips.at(-1).currentTime,words:[...document.querySelectorAll('[data-speech-active]')].map(e=>e.textContent)}));await p.waitForTimeout(350);const after=await p.evaluate(()=>({time:window.playfulClips.at(-1).currentTime,words:[...document.querySelectorAll('[data-speech-active]')].map(e=>e.textContent)}));assert.equal(after.time,frozen.time);assert.deepEqual(after.words,frozen.words);await p.locator('[data-action=playful-pause]').click();await expect.poll(()=>p.evaluate(()=>window.playfulClips.at(-1).currentTime)).toBeGreaterThan(frozen.time);await p.locator('[data-action=playful-home]').click();assert.equal(await p.locator('[data-speech-active]').count(),0);assert(await p.evaluate(()=>window.playfulClips.every(a=>a.paused)));report.playback.push({speed,wordHighlight:true,pauseResume:true,homeStops:true});
 await open('story:cat-rat','paragraph',speed);await p.locator('[data-action=playful-audio]').click();await expect.poll(()=>p.locator('.story-line [data-speech-active]').count()).toBeGreaterThan(0);await p.locator('[data-action=playful-audio]').click();await expect.poll(()=>p.evaluate(()=>window.playfulClips.at(-1)?.currentTime||0)).toBeGreaterThan(.05);assert(await p.evaluate(()=>window.playfulClips.filter(a=>!a.paused).length<=1));report.playback.push({speed,paragraphWordHighlight:true,replayNoOverlap:true});
}
await open('story:values-bismillah-bite','predict');await p.locator('.story-parents summary').click();await p.locator('[data-action=playful-note]').first().click();await expect.poll(()=>p.evaluate(()=>window.playfulClips.at(-1)?.currentTime||0)).toBeGreaterThan(.1);await p.locator('[data-action=playful-stop]').click();assert(await p.evaluate(()=>window.playfulClips.every(a=>a.paused)));report.playback.push({banglaExplanation:true,stop:true});
await open('word:cat','hidden');await p.locator('.math-meaning summary').first().click();await p.locator('[data-action=playful-bangla][data-part=meaning]').click();await expect.poll(()=>p.evaluate(()=>window.playfulClips.at(-1)?.currentTime||0)).toBeGreaterThan(.1);assert((await p.evaluate(()=>window.playfulClips.at(-1).src)).endsWith('/audio/5792efa2210c3cf0eb2708ec.mp3'));await p.locator('[data-action=playful-bangla][data-part=approx]').click();await expect.poll(()=>p.evaluate(()=>window.playfulClips.at(-1)?.currentTime||0)).toBeGreaterThan(.1);assert((await p.evaluate(()=>window.playfulClips.at(-1).src)).endsWith('/audio/34a66d51ccbadd137e895769.mp3'));report.playback.push({existingBanglaWordMeaning:true,existingPronunciationHelp:true,noOverlap:await p.evaluate(()=>window.playfulClips.filter(a=>!a.paused).length===1)});
await open('story:values-brother-friend','paragraph');await p.locator('[data-action=playful-audio]').click();await expect.poll(()=>p.evaluate(()=>window.playfulClips.length),{timeout:35000}).toBe(6);const refugeSources=await p.evaluate(()=>window.playfulClips.map(a=>new URL(a.src).pathname));assert(refugeSources.includes(stageSpeech['value-refuge-arabic']));assert.equal(refugeSources.at(-1),stageSpeech['text:We build the tower together.']);assert(!refugeSources.some(src=>src===stageSpeech['text:I say, “A‘udhu billahi min ash-shaytan ir-rajim.”']));report.playback.push({fullFiveSentenceParagraph:true,arabicSeparateRecording:true,noEnglishTransliteration:true});
assert.deepEqual(errors,[]);await writeFile('qa/playful-audio-report.json',JSON.stringify(report,null,2));await browser.close();console.log('PASS',report.newRecordings,'decoded recordings;',report.playback.length,'real playback checks; human listening remains needed');
