import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {execFileSync} from 'node:child_process';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {stageSpeech} from '../dist/stage-speech.js';
const oldCommit='b66e7c0',previousCommit='4e61a5399144d93924dac017043ab26d102b4a2a',root=resolve('dist'),versions=new Map();let revision=1;
const server=http.createServer(async(req,res)=>{const path=new URL(req.url,'http://localhost').pathname,name=path==='/'?'index.html':path.slice(1),filename=resolve(root,name);if(!filename.startsWith(root))return res.writeHead(404).end();try{let body;if(revision<3&&!name.startsWith('audio/')){const key=revision+':'+name;if(!versions.has(key))versions.set(key,execFileSync('git',['show',(revision===1?oldCommit:previousCommit)+':dist/'+name],{maxBuffer:20*1024*1024,stdio:['ignore','pipe','ignore']}));body=versions.get(key);}else body=await readFile(filename);res.writeHead(200,{'Content-Type':({'.js':'text/javascript','.webmanifest':'application/manifest+json','.html':'text/html','.css':'text/css','.mp3':'audio/mpeg','.wav':'audio/wav','.png':'image/png'}[extname(filename)]||'application/octet-stream'),'Cache-Control':'no-cache'});res.end(body);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(4176,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[],report={};page.on('pageerror',e=>errors.push(e.message));
try{
 await page.addInitScript(()=>localStorage.setItem('little-english-opening-audio-v1',JSON.stringify({version:1,enabled:false})));await page.goto('http://localhost:4176');await page.waitForFunction(async()=>{const reg=await navigator.serviceWorker.getRegistration();return reg?.active?.state==='activated';});await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await expect(page.locator('.home-stage')).toHaveCount(4);
 // Seed both profiles with actual old storage conventions, including saved ink.
 await page.evaluate(async()=>{const {hydrateProfiles,syncProfile,selectProfile}=await import('/progress-store.js'),{recordAttempt}=await import('/practice-data.js');const p=hydrateProfiles(null);p.learning.letter=1;p.lastActivity={kind:'stage',page:'letter',index:1};p.pictureFamilies.writing.current='cat';p.pictureFamilies.writing.drafts.cat={drawing:[[[.2,.2],[.3,.7]]],showGuide:false};recordAttempt(p.practice,'word:cat',false);syncProfile(p,'little');selectProfile(p,'big');p.learning.letter=3;p.learning.stories['pig-pen']={phase:'blanks',line:1,blank:0,answers:['sit'],done:false};p.lastActivity={kind:'stage',page:'story',id:'pig-pen'};recordAttempt(p.practice,'word:pig',false);syncProfile(p,'big');selectProfile(p,'little');localStorage.setItem('little-english-v1',JSON.stringify(p));localStorage.setItem('parent-sentinel','keep');});await page.reload();await expect(page.locator('[data-action=continue-home]')).toContainText('Bb');
 const clip=stageSpeech['word:cat'];await page.evaluate(async clip=>{await fetch(clip);},clip);await page.waitForFunction(async clip=>!!await (await caches.open('little-english-audio-v1')).match(clip),clip);
 revision=2;await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await page.waitForFunction(async()=>!!(await navigator.serviceWorker.getRegistration())?.waiting);
 await page.reload();await expect(page.locator('.home-stage')).toHaveCount(4);report.cause={oldCommit,serverCommit:previousCommit,newWorkerWaiting:true,oldCardsStillDisplayed:4};
 const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));let navigations=0;page.on('framenavigated',f=>{if(f===page.mainFrame())navigations++;});revision=3;await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await expect(page.locator('.home-stage')).toHaveCount(6,{timeout:30000});await page.waitForFunction(async()=>!(await navigator.serviceWorker.getRegistration())?.waiting);
 const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));assert.equal(after.profile,'little');for(const key of ['little','big']){assert.equal(after.profileData[key].learning.letter,before.profileData[key].learning.letter);assert.deepEqual(after.profileData[key].learning.stories,before.profileData[key].learning.stories);assert.deepEqual(after.profileData[key].pictureFamilies,before.profileData[key].pictureFamilies);assert.deepEqual(after.profileData[key].practice,before.profileData[key].practice);assert.deepEqual(after.profileData[key].lastActivity,before.profileData[key].lastActivity);}assert.equal(await page.evaluate(()=>localStorage.getItem('parent-sentinel')),'keep');assert.equal(navigations,1);const automaticRefreshes=navigations;
 await expect(page.locator('[data-action=continue-home]')).toContainText('Bb');await page.locator('.home-stage[data-stage=math]').click();await expect(page.locator('.math-lesson-card')).toHaveCount(12);await page.locator('[data-action=home]').first().click();await page.locator('.home-stage[data-stage=science]').click();await expect(page.locator('.science-lesson-card')).toHaveCount(10);await page.locator('[data-action=home]').first().click();
 await page.waitForFunction(async()=>{const keys=await caches.keys();return keys.length===2&&keys.some(k=>k.includes('all-sections-art-v2'));});assert(await page.evaluate(async clip=>!!await (await caches.open('little-english-audio-v1')).match(clip),clip));await context.setOffline(true);await page.reload();await expect(page.locator('.home-stage')).toHaveCount(6);await page.locator('.home-stage[data-stage=math]').click();await expect(page.locator('.math-lesson-card')).toHaveCount(12);await page.locator('[data-action=home]').first().click();await page.locator('.home-stage[data-stage=science]').click();await expect(page.locator('.science-lesson-card')).toHaveCount(10);assert.deepEqual(errors,[]);
 report.fix={cards:6,automaticRefreshes,bothProfilesPreserved:true,writingPreserved:true,historyPreserved:true,audioRetained:true,offlineMathAndScience:true};report.passed=true;await writeFile('qa/pwa-upgrade-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{await context.close();await browser.close();await new Promise(r=>server.close(r));}
