import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {stageSpeech} from '../dist/stage-speech.js';
import {openingAudioSource} from '../dist/opening-audio-data.js';
let revision=1;const root=resolve('dist');
const server=http.createServer(async(req,res)=>{const path=new URL(req.url,'http://localhost').pathname,filename=resolve(root,'.'+(path==='/'?'/index.html':path));if(!filename.startsWith(root))return res.writeHead(404).end();try{let body=await readFile(filename);if(path==='/sw.js')body=Buffer.from(body.toString().replace(/const APP_VERSION='[^']+';/,"const APP_VERSION='little-english-pwa-test"+revision+"';"));res.writeHead(200,{'Content-Type':({'.js':'text/javascript','.webmanifest':'application/manifest+json','.html':'text/html','.css':'text/css','.mp3':'audio/mpeg','.wav':'audio/wav','.png':'image/png'}[extname(filename)]||'application/octet-stream'),'Cache-Control':'no-cache'});res.end(body);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(4175,'127.0.0.1',r));
const context=await chromium.launchPersistentContext('.sites-runtime/pwa-profile-'+Date.now(),{channel:'msedge',headless:true,viewport:{width:390,height:844}}),page=await context.newPage(),errors=[],report={};page.on('pageerror',e=>errors.push(e.message));
try{
 await page.addInitScript(()=>localStorage.setItem('little-english-opening-audio-v1',JSON.stringify({version:1,enabled:false})));await page.goto('http://localhost:4175');await page.waitForFunction(async()=>{const reg=await navigator.serviceWorker.getRegistration();return reg?.active?.state==='activated';});await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 const cdp=await context.newCDPSession(page),manifest=await cdp.send('Page.getAppManifest');assert.equal(manifest.errors.length,0);const parsed=JSON.parse(manifest.data);assert.equal(parsed.display,'standalone');assert.equal(parsed.start_url,'/');assert.deepEqual(parsed.icons.map(i=>i.sizes),['192x192','512x512','512x512']);
 const install=await cdp.send('Page.getInstallabilityErrors');assert.deepEqual(install.installabilityErrors,[]);report.installability={browser:'Edge Chromium',errors:install.installabilityErrors,manifest:true};
 // Browser-dispatched prompt wiring is separately checked; headless OS installation unavailable.
 await page.locator('[data-action=parents]').click();await page.evaluate(()=>{const e=new Event('beforeinstallprompt');e.prompt=async()=>{window.promptCalled=true;};e.userChoice=Promise.resolve({outcome:'accepted'});dispatchEvent(e);});await page.locator('[data-action=pwa-install]').click();assert(await page.evaluate(()=>window.promptCalled));report.installButton={promptWiring:true,syntheticEvent:true};
 const clip=stageSpeech['word:cat'];await page.evaluate(async clip=>{const audio=new Audio(clip);window.clip=audio;await audio.play();},clip);await page.waitForFunction(()=>window.clip.ended);await page.waitForFunction(async clip=>!!await (await caches.open('little-english-audio-v1')).match(clip),clip);
 await page.locator('[data-action=home]').first().click();await page.locator('[data-action=start-home]').click();await page.locator('[data-action=stages-alphabet-next]').click();await page.locator('.letter-paging [data-index="1"]').click();await page.locator('[data-action=home]').first().click();const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));
 await context.setOffline(true);await page.reload();await expect(page.locator('[data-action=continue-home]')).toContainText('Bb');await page.locator('[data-action=continue-home]').click();await expect(page.locator('h1')).toContainText('Bb');await page.evaluate(async clip=>{window.clip=new Audio(clip);await window.clip.play();},clip);await page.waitForFunction(()=>window.clip.ended);report.offline={shell:true,lesson:true,progress:true,playedAudio:true};
 await context.setOffline(false);await page.locator('[data-action=parents]').click();revision=2;await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});// The complete new shell activates and refreshes automatically, including older clients.
 await expect(page.locator('[data-action=continue-home]')).toContainText('Bb');await page.waitForFunction(async()=>{const keys=await caches.keys();return keys.some(k=>k.includes('test2'))&&!keys.some(k=>k.includes('test1'));});const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));assert.deepEqual(after.learning,before.learning);assert.deepEqual(after.profileData,before.profileData);report.update={newVersionActive:true,oldShellRemoved:true,audioRetained:true,profilesPreserved:true};
 // The revised immutable opening clip is fetched and cached separately from
 // the retained lesson audio; profile records never enter either cache.
 const opening=openingAudioSource.clip;await page.evaluate(async clip=>{window.openingCheck=new Audio(clip);await window.openingCheck.play();},opening);await page.waitForFunction(()=>window.openingCheck.ended);await page.waitForFunction(async clip=>!!await (await caches.open('little-english-audio-v1')).match(clip),opening);await context.setOffline(true);await page.evaluate(async clip=>{window.openingCheck=new Audio(clip);await window.openingCheck.play();},opening);await page.waitForFunction(()=>window.openingCheck.ended);await context.setOffline(false);report.revisedOpening={clip:opening,playedOnline:true,cached:true,playedOffline:true};
 // Newly shipped science modules and illustrations are part of the same offline shell.
 await page.locator('.home-stage[data-stage=science]').click();await page.locator('[data-action=stages-science-open][data-id=science-float]').click();await page.locator('[data-action=playful-reread]').click();for(let i=0;i<4;i++)await page.locator('[data-action=stages-science-next]').click();await context.setOffline(true);await page.locator('[data-action=stages-science-explore][data-value=key]').click();await expect(page.locator('.science-player>.science-scene')).toHaveAttribute('data-science-scene','float-key');await page.locator('[data-action=home]').first().click();await page.reload();await page.locator('[data-action=continue-home]').click();await expect(page.locator('.science-player')).toHaveAttribute('data-science-step','4');await expect(page.locator('[data-action=stages-science-next]')).toBeDisabled();await page.locator('[data-action=stages-science-explore][data-value=wood]').click();await expect(page.locator('.science-player>.science-scene')).toHaveAttribute('data-science-scene','float-wood');assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')))).learning.letter,before.learning.letter);report.offlineScience={cachedModules:true,interactiveScene:true,unfinishedExperimentResumed:true,oldLetterPositionPreserved:true};
 await context.setOffline(false);await page.locator('[data-action=home]').first().click();await page.locator('.home-stage[data-stage=science]').click();await page.locator('[data-action=stages-science-open][data-id=science-switch]').click();await page.locator('[data-action=playful-skip-words]').click();await context.setOffline(true);await page.locator('[data-science-object=switch]').click();await expect(page.locator('[data-science-scene=lamp-on]')).toBeVisible();await page.locator('[data-action=playful-home]').click();await page.reload();await page.locator('[data-action=continue-home]').click();await expect(page.locator('.playful-player')).toHaveAttribute('data-playful-type','switch');await page.locator('[data-science-object=switch]').click();await expect(page.locator('[data-science-scene=lamp-off]')).toBeVisible();report.offlinePlayful={newModulesCached:true,tapScene:true,unfinishedActionResumed:true};
 assert.deepEqual(errors,[]);report.passed=true;report.limitations=['Headless Edge verifies installability and prompt integration, not a physical Home Screen installation','Android browser UI and iOS/iPadOS Safari Add to Home Screen require physical-device testing','Existing URL is preserved; website and PWA share the same shipped sources'];await writeFile('qa/pwa-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{await context.close();await new Promise(r=>server.close(r));}
