import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {letters,profiles,normalizeProgress} from '../dist/curriculum.js';
assert.equal(Object.keys(letters).length,26);
assert.equal(new Set(profiles.little.lessons.flatMap(l=>l.items)).size,26);
assert.equal(profiles.little.lessons.flatMap(l=>l.items).length,26);
assert.equal(profiles.big.lessons.flatMap(l=>l.items).length,54);
for(const lesson of profiles.big.lessons){assert(lesson.choices.includes(lesson.answer));for(const word of lesson.items){assert([3,4].includes(word.length));for(const letter of word)assert(letters[letter]);}}
assert.deepEqual(normalizeProgress({completed:{little:['letters-sat','letters-sat','bad'],big:['letters-sat']}}).completed,{little:['letters-sat'],big:[]});
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100}});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const external=[];page.on('request',r=>{if(!r.url().startsWith('http://localhost:4174/')&&!r.url().startsWith('data:'))external.push(r.url());});
await page.goto('http://localhost:4174');
await expect(page.getByRole('heading',{name:'Hello, little learners.'})).toBeVisible();
await page.screenshot({path:'qa/home-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Start lesson'}).click();
await expect(page.getByRole('heading',{name:'Say hello to S and s.'})).toBeVisible();
await page.screenshot({path:'qa/letter-desktop.png',fullPage:true});
for(let i=0;i<3;i++)await page.getByRole('button',{name:'Next →',exact:true}).click();
await page.getByRole('button',{name:/Lowercase (?!s$)/}).first().click();
await expect(page.getByRole('status').filter({hasText:'Good try'})).toBeVisible();
await expect(page.getByRole('button',{name:'Next →',exact:true})).toHaveCount(0);
for(const c of ['s','a','t']){await page.getByRole('button',{name:`Lowercase ${c}`,exact:true}).click();await page.getByRole('button',{name:'Next →',exact:true}).click();}
const bounds=await page.locator('canvas').boundingBox();
await page.mouse.move(bounds.x+30,bounds.y+30);await page.mouse.down();await page.mouse.move(bounds.x+100,bounds.y+100,{steps:8});await page.mouse.up();
assert(await page.locator('canvas').evaluate(c=>c.getContext('2d').getImageData(0,0,c.width,c.height).data.some(v=>v>0)));
await page.getByRole('button',{name:'Clear drawing',exact:true}).click();
assert(!(await page.locator('canvas').evaluate(c=>c.getContext('2d').getImageData(0,0,c.width,c.height).data.some(v=>v>0))));
for(let i=0;i<3;i++)await page.getByRole('button',{name:'We practised →',exact:true}).click();
await page.getByRole('button',{name:'We tried it! Finish ★',exact:true}).click();
await expect(page.getByRole('heading',{name:'You did it, Little Explorer!'})).toBeVisible();
await page.getByRole('button',{name:'Back to my path',exact:true}).click();
await page.reload();await expect(page.getByText('1 of 9 lessons explored')).toBeVisible();
await page.getByRole('button',{name:/Word Adventurer Age 6/}).click();
await expect(page.getByText('0 of 18 lessons explored')).toBeVisible();
await page.getByRole('button',{name:'Start lesson'}).click();
for(let i=0;i<3;i++)await page.getByRole('button',{name:'Let’s try →',exact:true}).click();
for(const c of ['t','a','c'])await page.getByRole('button',{name:`Letter ${c}`,exact:true}).click();
await expect(page.locator('#feedback').filter({hasText:'Let’s try that again.'})).toBeVisible();
await expect(page.getByRole('button',{name:'Next →',exact:true})).toHaveCount(0);
await page.getByRole('button',{name:'Try the letters again',exact:true}).click();
await page.screenshot({path:'qa/build-desktop.png',fullPage:true});
for(const word of ['cat','mat','sat']){for(const c of word)await page.getByRole('button',{name:`Letter ${c}`,exact:true}).click();await page.getByRole('button',{name:'Next →',exact:true}).click();}
for(const word of ['cat','mat','sat']){await page.getByRole('button',{name:word,exact:true}).click();await page.getByRole('button',{name:'Next →',exact:true}).click();}
await expect(page.getByText('A cat sat.',{exact:true})).toBeVisible();
await page.getByRole('button',{name:'cat',exact:true}).click();await page.getByRole('button',{name:'Next →',exact:true}).click();
await page.getByRole('button',{name:'We tried it! Finish ★',exact:true}).click();
await page.getByRole('button',{name:'Back to my path',exact:true}).click();await page.reload();
await expect(page.getByText('1 of 18 lessons explored')).toBeVisible();
const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('little-english-v1')));
assert.deepEqual(persisted.completed,{little:['letters-sat'],big:['words-1']});
await page.getByRole('button',{name:'For parents',exact:true}).click();
await expect(page.getByRole('heading',{name:'Letter names and sounds are different'})).toBeVisible();
await page.waitForFunction(()=>speechSynthesis.getVoices().length>0,{timeout:5000}).catch(()=>{});
const speech=await page.evaluate(()=>({supported:'speechSynthesis'in window,voices:speechSynthesis.getVoices().filter(v=>v.localService&&/^en([-_]|$)/i.test(v.lang)).map(v=>({name:v.name,lang:v.lang}))}));
await page.getByRole('button',{name:'Test voice',exact:true}).click();
await page.screenshot({path:'qa/parents-desktop.png',fullPage:true});
await page.getByRole('button',{name:'← Learning path',exact:true}).click();
await page.getByRole('button',{name:'Open the alphabet',exact:true}).click();
await expect(page.getByRole('button',{name:/^Explore /})).toHaveCount(26);
await page.getByRole('button',{name:'Explore X x',exact:true}).click();
await expect(page.getByText('Listen at the END of box.',{exact:false})).toBeVisible();
await page.getByRole('button',{name:'← Learning path',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'qa/home-mobile.png',fullPage:true});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.getByRole('button',{name:'Start lesson'}).click();
await page.screenshot({path:'qa/lesson-mobile.png',fullPage:true});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.getByRole('button',{name:'For parents',exact:true}).click();
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
const modelContext=await page.evaluate(()=>!!document.modelContext?.registerTool);
const report={passed:true,checks:['27 lesson data sets valid','26 letters introduced exactly once','incorrect answers allow retry and cannot advance','drawing and clearing work','both first lessons completed through the UI','progress persists after reload and stays separate','alphabet has all 26 letters','parent guide and voice controls render','390px mobile layouts do not overflow','no page errors or external page requests'],speech,webMcpAvailable:modelContext};
await writeFile('qa/report.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
await browser.close();
